config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages/index', to: 'static_pages#index'
  get '/works', to: 'static_pages#works'
  get '/works/:id', to: 'static_pages#work', as: :work
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  namespace :admin do
    resources :users, only: [:edit, :show, :index, :update]
    resources :works
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :works
end

app/models/work.rb
class Work < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
  mount_uploader :image, ImageUploader
  scope :recent, -> { order(created_at: :desc) }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation, :introduction, :skill_title_1, :skill_title_2, :skill_title_3, :skill_description_1, :skill_description_2, :skill_description_3, :skill_icon_1, :skill_icon_2, :skill_icon_3)
    end

    def require_admin
      redirect_to root_path unless current_user.admin?
    end
end

app/controllers/admin/works_controller.rb
class Admin::WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  def new
    @work = Work.new
  end

  def index
    @works = current_user.works.recent
  end

  def show
  end

  def edit
  end

  def create
    @work = current_user.works.new(work_params)
    if @work.save
      redirect_to admin_work_path(@work), notice: "「#{@work.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    if @work.update(work_params)
      redirect_to admin_work_path(@work), notice: "「#{@work.name}」を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @work.destroy
    redirect_to admin_works_path, notice: "「#{@work.name}」を削除しました。"
  end

  private
    def work_params
      params.require(:work).permit(:name, :summary, :description, :repository, :production, :image)
    end

    def set_work
      @work = current_user.works.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private
    def current_user
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def login_required
      redirect_to login_path unless current_user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to admin_works_path, notice: 'ログインしました。'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to login_path, notice: 'ログアウトしました。'
  end

  private
    def session_params
      params.require(:session).permit(:email, :password)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout "static_pages"
  skip_before_action :login_required

  def index
    @user = User.find_by(admin: true)
    @works = Work.all.order(created_at: :desc).limit(4)
    @works_count = Work.all.size
  end

  def works
    @works = Work.all.order(created_at: :desc)
  end

  def work
    @work = Work.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Portfolio"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def display_work_image(work)
    if work.image?
      image_tag(work.image.url, class: "work-image", alt: "制作事例:#{work.name}")
    else
      image_tag("/assets/tree.jpg", class: "work-image", alt: "制作事例:#{work.name}")
    end
  end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/admin/users/_user.html.erb
<tr>
  <td><%= link_to user.name, admin_user_path(user) %></td>
  <td><%= user.email %></td>
  <td><%= user.admin %></td>
  <td><%= user.created_at %></td>
  <td><%= user.updated_at %></td>
  <td>
    <%= link_to '詳細', admin_user_path(user), class: 'btn btn-primary' %>
    <%= link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary' %>
  </td>
</tr>

app/views/admin/users/edit.html.erb
<% provide(:title, "ユーザーの編集") %>

<h1 class="my-5">ユーザーの編集</h1>

<div class="nav justify-content-end">
  <%= link_to '一覧に戻る', admin_users_path, class: 'nav-link' %>
</div>

<% if @user.errors.present? %>
  <ul id="error_explanation">
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: [:admin, @user], local: true do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :introduction %>
    <%= form.text_area :introduction, rows: 5, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :skill_icon_1 %>
    <%= form.text_field :skill_icon_1, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :skill_title_1 %>
    <%= form.text_field :skill_title_1, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :skill_description_1 %>
    <%= form.text_area :skill_description_1, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :skill_icon_2 %>
    <%= form.text_field :skill_icon_2, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :skill_title_2 %>
    <%= form.text_field :skill_title_2, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :skill_description_2 %>
    <%= form.text_area :skill_description_2, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :skill_icon_3 %>
    <%= form.text_field :skill_icon_3, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :skill_title_3 %>
    <%= form.text_field :skill_title_3, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :skill_description_3 %>
    <%= form.text_area :skill_description_3, class: 'form-control' %>
  </div>
  <div class="form-check">
    <%= form.label :admin, class: 'form-check-label' do %>
      <%= form.check_box :admin, class: 'form-check-input' %>
      管理者権限
    <% end %>
  </div>
  <div class="form-group">
    <%= form.label :password, 'パスワード' %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :password_confirmation, 'パスワード（確認）' %>
    <%= form.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <%= form.submit '更新する', class: 'btn btn-primary' %>
<% end %>

app/views/admin/users/index.html.erb
<% provide(:title, "ユーザー一覧") %>

<h1 class="my-5 text-center">ユーザー一覧</h1>

<div>
  <table class="table table-hover">
    <thead class="thead-default">
      <tr>
        <th><%= User.human_attribute_name(:name) %></th>
        <th><%= User.human_attribute_name(:email) %></th>
        <th><%= User.human_attribute_name(:admin) %></th>
        <th><%= User.human_attribute_name(:created_at) %></th>
        <th><%= User.human_attribute_name(:updated_at) %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render @users %>
    </tbody>
  </table>
</div>

app/views/admin/users/show.html.erb
<% provide(:title, "ユーザー詳細") %>

<h1 class="my-5">ユーザー詳細</h1>

<div class="nav justify-content-end">
  <%= link_to '一覧に戻る', admin_users_path, class: 'nav-link' %>
</div>

<table class="table table-hover">
  <tbody>
    <tr>
      <th><%= User.human_attribute_name(:name) %></th>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:email) %></th>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:introduction) %></th>
      <td><%= auto_link(simple_format(h(@user.introduction), {}, sanitize: false, wrapper_tag: "div")) %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:skill_icon_1) %></th>
      <td><i class="<%="skill-icon #{@user.skill_icon_1}" %>"></i></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:skill_title_1) %></th>
      <td><%= @user.skill_title_1 %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:skill_description_1) %></th>
      <td><%= @user.skill_description_1 %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:skill_icon_2) %></th>
      <td><i class="<%="skill-icon #{@user.skill_icon_2}" %>"></i></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:skill_title_2) %></th>
      <td><%= @user.skill_title_2 %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:skill_description_2) %></th>
      <td><%= @user.skill_description_2 %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:skill_icon_3) %></th>
      <td><i class="<%="skill-icon #{@user.skill_icon_3}" %>"></i></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:skill_title_3) %></th>
      <td><%= @user.skill_title_3 %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:skill_description_3) %></th>
      <td><%= @user.skill_description_3 %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:admin) %></th>
      <td><%= @user.admin %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:created_at) %></th>
      <td><%= @user.created_at %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:updated_at) %></th>
      <td><%= @user.updated_at %></td>
    </tr>
  </tbody>
</table>

<%= link_to '編集', edit_admin_user_path(@user), class: 'btn btn-primary mr-3' %>

app/views/admin/works/_form.html.erb
<% if work.errors.present? %>
  <ul id="error_explanation">
    <% work.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: [:admin, work], local: true do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', id: 'work_name' %>
  </div>
  <div class="form-group">
    <%= form.label :summary %>
    <%= form.text_field :summary, class: 'form-control', id: 'work_summary' %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 5, class: 'form-control', id: 'work_description' %>
  </div>
  <div class="form-group">
    <%= form.label :repository %>
    <%= form.text_field :repository, class: 'form-control', id: 'work_repository' %>
  </div>
  <div class="form-group">
    <%= form.label :production %>
    <%= form.text_field :production, class: 'form-control', id: 'work_production' %>
  </div>
  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, accept: 'image/jpeg,image/gif,image/png', class: 'form-control' %>
    <p class="form_alert">画像サイズは1MB以下までアップロード可能です。</p>
  </div>
  <%= form.submit nil, class: 'btn btn-primary' %>
<% end %>

app/views/admin/works/_work.html.erb
<tr>
  <td><%= link_to work.name, admin_work_path(work) %></td>
  <td><%= work.created_at %></td>
  <td><%= work.updated_at %></td>
  <td>
    <%= link_to '詳細', admin_work_path(work), class: 'btn btn-primary' %>
    <%= link_to '編集', edit_admin_work_path(work), class: 'btn btn-primary' %>
    <%= link_to '削除', [:admin, work], method: :delete, data: { confirm: "「#{work.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/works/edit.html.erb
<% provide(:title, "作品の編集") %>

<h1 class="my-5 text-center">作品の編集</h1>

<div class="nav justify-content-end">
  <%= link_to '一覧に戻る', admin_works_path, class: 'nav-link' %>
</div>

<%= render 'form', work: @work %>

app/views/admin/works/index.html.erb
<% provide(:title, "作品一覧") %>

<h1 class="my-5 text-center">作品一覧</h1>
<%= link_to '新規登録' ,new_admin_work_path, class: 'btn btn-primary' %>
<div class="mt-3">
  <table class="table table-hover">
    <thead class="thead-default">
      <tr>
        <th><%= User.human_attribute_name(:name) %></th>
        <th><%= User.human_attribute_name(:created_at) %></th>
        <th><%= User.human_attribute_name(:updated_at) %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render @works %>
    </tbody>
  </table>
</div>

app/views/admin/works/new.html.erb
<% provide(:title, "作品の登録") %>

<h1 class="my-5 text-center">作品の登録</h1>

<div class="nav justify-content-end">
  <%= link_to '一覧に戻る', admin_works_path, class: 'nav-link' %>
</div>

<%= render 'form', work: @work %>

app/views/admin/works/show.html.erb
<% provide(:title, "作品詳細") %>

<h1 class="my-5 text-center">作品詳細</h1>

<div class="nav justify-content-end">
  <%= link_to '一覧に戻る', admin_works_path, class: 'nav-link' %>
</div>

<table class="table table-hover">
  <tbody>
    <tr>
      <th><%= Work.human_attribute_name(:name) %></th>
      <td><%= @work.name %></td>
    </tr>
    <tr>
      <th><%= Work.human_attribute_name(:summary) %></th>
      <td><%= @work.summary %></td>
    </tr>
    <tr>
      <th><%= Work.human_attribute_name(:description) %></th>
      <td><%= auto_link(simple_format(h(@work.description), {}, sanitize: false, wrapper_tag: "div")) %></td>
    </tr>
    <tr>
      <th><%= Work.human_attribute_name(:repository) %></th>
      <td><%= auto_link(@work.repository, html: { target: '_blank' }) %></td>
    </tr>
    <tr>
      <th><%= Work.human_attribute_name(:production) %></th>
      <td><%= auto_link(@work.production, html: { target: '_blank' }) %></td>
    </tr>
    <tr>
      <th><%= Work.human_attribute_name(:image) %></th>
      <td><%= image_tag @work.image.url if @work.image? %></td>
    </tr>
    <tr>
      <th><%= Work.human_attribute_name(:created_at) %></th>
      <td><%= @work.created_at %></td>
    </tr>
    <tr>
      <th><%= Work.human_attribute_name(:updated_at) %></th>
      <td><%= @work.updated_at %></td>
    </tr>
  </tbody>
</table>

<%= link_to '編集', edit_admin_work_path(@work), class: 'btn btn-primary mr-3' %>
<%= link_to '削除', [:admin, @work], method: :delete, data: { confirm: "「#{@work.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger' %>

app/views/layouts/_footer.html.erb
<footer class="py-5 mt-5 bg-dark text-white">
<p class="text-center mb-0"><small>&copy; 2019 Shogo Harada</small></p>
</footer>

app/views/layouts/_header.html.erb
<div class="app-title navbar navbar-expand-md navbar-light bg-light">
  <div class="navbar-brand">Portfolio管理画面</div>
  <ul class="navbar-nav ml-auto">
    <% if current_user %>
      <li class="nav-item"><%= link_to "Portfolio", root_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to "User", admin_users_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to "Work", admin_works_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to "Logout", logout_path, method: :delete, class: 'nav-link' %></li>
    <% else %>
      <li class="nav-item"><%= link_to "Login", login_path, class: 'nav-link' %></li>
    <% end %>
  </ul>
</div>
<% if flash.notice.present? %>
  <div class="alert alert-success">
    <%= flash.notice %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">

      <%= yield %>

    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/static_pages.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    <%= stylesheet_link_tag 'open/static_pages', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= "bg-image" if controller.action_name == 'index' %>">  
    <% if current_user %>
      <div class="admin-menu">
        <%= link_to "管理画面", admin_works_path, class: 'nav-link' %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/_footer.html.erb
<footer class="sub-footer">
  &copy; Shogo
</footer>

app/views/static_pages/_work.html.erb
<div class="work-box">
  <div class="work-box-inner">
    <div class="work-image-box">
      <%= display_work_image(work) %>
    </div>
    <div class="work-text">
      <p class="work-title"><%= work.name %></p>
      <div class="work-description">
        <p><%= work.summary %></p>
      </div>
      <p><%= link_to "リポジトリ", work.repository, target: "_blank" %><%= link_to " / 公開サイト", work.production, target: "_blank" %></p>
      <%= link_to 'READ MORE', work_path(work), class: 'button button-ghost' %>
    </div>
  </div>
</div>

app/views/static_pages/index.html.erb
<header class="header">
  <p class="site-title-sub">Web Enginner</p>
  <h1 class="site-title">Shogo's Portfolio</h1>
  <p class="site-description">Check out some of my works.</p>
  <div class="buttons">
    <%= link_to "LEARN MORE", "#about", class: "button" %>
    <%= link_to "SEND MESSAGE", "#contact", class: "button button-showy" %>
  </div>
</header>
<section id="about" class="about">
  <div><h2 class="heading">ABOUT</h2></div>
  <div class="about-text">
    <p><%= simple_format(h(@user.introduction)) %></p>
  </div>
</section>
<section class="works">
  <h2 class="heading">WORKS</h2>
  <div class="works-wrapper">
    <%= render partial: 'static_pages/work', collection: @works %>
    <%= link_to 'もっと見る', works_path, class: "work-link" if @works_count > 4 %>
  </div>
</section>
<section class="skills">
  <h2 class="heading">SKILLS</h2>
  <div class="skills-wrapper">
    <div class="skill-box">
      <i class="<%= "skill-icon #{@user.skill_icon_1}" %>"></i>
      <div class="skill-title"><%= @user.skill_title_1 %></div>
      <div class="skill-text">
        <%= simple_format(h(@user.skill_description_1)) %>
      </div>
    </div>
    <div class="skill-box">
      <i class="<%= "skill-icon #{@user.skill_icon_2}" %>"></i>
      <div class="skill-title"><%= @user.skill_title_2 %></div>
      <div class="skill-text">
        <%= simple_format(h(@user.skill_description_2)) %>
      </div>
    </div>
    <div class="skill-box">
      <i class="<%= "skill-icon #{@user.skill_icon_3}" %>"></i>
      <div class="skill-title"><%= @user.skill_title_3 %></div>
      <div class="skill-text">
        <%= simple_format(h(@user.skill_description_3)) %>
      </div>
    </div>
  </div>
</section>
<section id="contact" class="contact">
  <h2 class="heading">CONTACT</h2>
  <div class="contact-wrapper">
    <%= link_to "mailto:harada.tosho.2016@gmail.com", class: "contact-mail" do %>
      <i class="contact-icon far fa-envelope"></i>
      harada.tosho.2016@gmail.com
    <% end %>
  </div>
  <%= link_to "https://bitbucket.org/shogo-h/", target: "_blank" do %>
    <i class="git-icon fab fa-bitbucket"></i>
  <% end %>
</section>
<footer class="footer">&copy; Shogo</footer>

app/views/static_pages/work.html.erb
<section class="works" style="background-image:none;">
  <div class="breadcrumbs">
    <%= link_to "TOP", root_path %>
    <span> / </span>
    <%= link_to "WORKS", works_path %>
    <span> / </span>
    <%= @work.name %>
  </div>
  <h2 class="heading"><%= @work.name %></h2>
  <div class="work-show">
    <%= display_work_image(@work) %>
    <div class="work-description">
      <p><%= simple_format(h(@work.description)) %></p>
    </div>
    <p><%= link_to "リポジトリ", @work.repository, target: "_blank" %>
      <%= link_to " / 公開サイト", @work.production, target: "_blank" %>
    </p>
  </div>
</section>
<%= render 'static_pages/footer' %>

app/views/static_pages/works.html.erb
<section class="works">
  <div class="breadcrumbs">
    <%= link_to "TOP", root_path %>
    <span> / </span>
    WORKS
  </div>
  <h2 class="heading">WORKS</h2>
  <div class="works-wrapper">
    <%= render partial: 'static_pages/work', collection: @works %>
  </div>
</section>
<%= render 'static_pages/footer' %>